[language-server]
clangd = { command = "clangd", args = [ "--clang-tidy" ] }

[[language]]
name = "cefre"
scope = "source.cfr"
injection-regex = "cfr"
file-types = ["cfr"]
comment-tokens = "#"
indent = { tab-width = 2, unit = "  " }
# formatter = { command = "cfr-formatter" , args = ["--stdin"] }
# language-servers = [ "cfr-lsp" ]

[[grammar]]
name = "cfr"
source = { path = "./tree-sitter-cfr" }
